/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}'],
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#eae8e3',
        'error-red': '#b30000',
        'action-blue': '#1863dc',
        'on-background': '#1b1c19',
        'primary': '#000000',
        'ink': '#212121',
        'muted-slate': '#93939f',
        'primary-container': '#1b1b20',
        'on-primary-container': '#848389',
        'background': '#fbf9f4',
        'hairline': '#d9d9dd',
        'surface-variant': '#e4e2dd',
        'surface-container-highest': '#e4e2dd',
        'form-focus-violet': '#9b60aa',
        'on-surface-variant': '#47464b',
        'surface-dim': '#dcdad5',
        'surface': '#fbf9f4',
        'slate': '#75758a',
        'secondary': '#35675d',
        'secondary-fixed-dim': '#9dd1c4',
        'surface-container-low': '#f5f3ee',
        'on-error': '#ffffff',
        'dark-navy': '#071829',
        'error-container': '#ffdad6',
        'surface-container': '#f0eee9',
        'on-surface': '#1b1c19',
        'focus-blue': '#4c6ee6',
        'canvas-white': '#ffffff',
        'outline-variant': '#c8c5cb',
        'soft-coral': '#ffad9b',
        'coral': '#ff7759',
        'surface-container-lowest': '#ffffff',
        'border-light': '#e5e7eb',
        'on-primary': '#ffffff',
        'surface-bright': '#fbf9f4',
        'on-secondary': '#ffffff',
        'secondary-container': '#b8ede0',
        'deep-green': '#003c33',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.5rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
        'card': '16px',
        'media': '22px',
      },
      spacing: {
        'xl': '32px',
        'sm': '8px',
        'xxl': '64px',
        'gutter': '16px',
        'lg': '24px',
        'xs': '4px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'unit': '8px',
        'md': '16px',
      },
      fontFamily: {
        'display': ['Space Grotesk', 'Inter', 'ui-sans-serif', 'system-ui'],
        'body': ['Inter', 'ui-sans-serif', 'system-ui'],
        'mono': ['JetBrains Mono', 'monospace'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'display-product': ['Space Grotesk', 'Inter', 'ui-sans-serif'],
        'headline-section': ['Inter', 'ui-sans-serif'],
        'headline-card': ['Inter', 'ui-sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif'],
        'caption': ['Inter', 'ui-sans-serif'],
        'button': ['Inter', 'ui-sans-serif'],
      },
      fontSize: {
        'display-hero': ['96px', { lineHeight: '96px', letterSpacing: '-1.92px', fontWeight: '400' }],
        'display-product': ['72px', { lineHeight: '72px', letterSpacing: '-1.44px', fontWeight: '400' }],
        'headline-section': ['48px', { lineHeight: '58px', letterSpacing: '-0.48px', fontWeight: '400' }],
        'headline-card': ['32px', { lineHeight: '38px', letterSpacing: '-0.32px', fontWeight: '400' }],
        'headline-section-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.32px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '25px', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'button': ['14px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '17px', letterSpacing: '0', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
